version: '3.3'
services:
  aerostack2:
    image: aerostack2:latest
    build:
      context: .
    container_name: aerostack2
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
    runtime: nvidia
    volumes:
      # display related 
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      # nvim related
      - ~/.config/nvim:/root/.config/nvim
      - ~/.config/coc:/root/.config/coc
      - ~/.config/github-copilot:/root/.config/github-copilot
      - ~/.local/share/nvim/:/root/.local/share/nvim/
      # tmux related
      - ~/.tmux:/root/.tmux
      - ~/.tmux.conf:/root/.tmux.conf
      # ssh related
      - ~/.ssh:/root/.ssh
      # working dirs
      - ~/aerostack2_ws:/root/aerostack2_ws

    network_mode: "host"
    command: tail -f /dev/null
