version: '3.3'
services:
  ros2:
    image: ros2 
    build:
      dockerfile: Dockerfile
    container_name: ros2
    command: tail -F anything 
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ~/.tmux:/root/.tmux
      - ~/.tmux.conf:/root/.tmux.conf
      - ~/.config/nvim:/root/.config/nvim
      - ~/.config/coc:/root/.config/coc
      - ~/.local/share/nvim/:/root/.local/share/nvim/
      - ~/curso_ros2:/root/curso_ros2
      # - ~/.shh:/root/.ssh
    network_mode: "host"
