services:
  aerostack2:
    image: aerostack2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerostack2
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
    privileged: true
    restart: always
    volumes:
      # display related 
      - ~/.Xauthority:/root/.Xauthority
      # ssh related
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # nvim related
      - ~/.config/nvim:/root/.config/nvim
      - ~/.config/coc:/root/.config/coc
      - ~/.config/github-copilot:/root/.config/github-copilot
      - ~/.local/share/nvim/:/root/.local/share/nvim/
      # tmux related
      - ~/.tmux:/root/.tmux
      - ~/.tmux.conf:/root/.tmux.conf
      # git
      - ~/.gitconfig:/root/.gitconfig_local
      # working dirs
      # - ./workspace:/root/aerostack2_ws/:rw
    network_mode: "host"
    command: tail -f /dev/null
