services:
  coresense_ros2:
    image: coresense_ros2
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: coresense_ros2
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    runtime: nvidia
    privileged: true
    restart: always
    volumes:
      # display related 
      - ~/.Xauthority:/root/.Xauthority:rw
      # ssh related
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # nvim related
      - ~/.config/nvim:/root/.config/nvim
      - ~/.config/coc:/root/.config/coc
      - ~/.config/github-copilot:/root/.config/github-copilot
      - ~/.local/share/nvim/:/root/.local/share/nvim/
      # tmux related
      - ~/.tmux:/root/.tmux:ro
      - ~/.tmux.conf:/root/.tmux.conf:ro
      # git
      - ~/.gitconfig:/root/.gitconfig_local:ro
      # working dirs
      - ./workspace:/root/workspace/
    network_mode: "host"
    command: tail -f /dev/null
